{% set name = "gsd" %}
{% set version = "2.0.0" %}
{% set sha256 = "659221326bf09548f0c8c0e4f9a781585891da41c70a8a62f186895739957eef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # the upstream package does not support python2.7
  skip: true  # [py27]
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - setuptools
    - cython
    - python
    - numpy
    - pip

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - gsd
    - gsd.fl
    - gsd.pygsd
    - gsd.hoomd
  source_files:
    - tests/
    - setup.cfg
  commands:
    - pytest

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'General simulation data'

  description: |
   GSD (General Simulation Data) is a file format specification
   and a library to read and write it. The package also contains a python module
   that reads and writes hoomd schema gsd files with an easy to use syntax.

  doc_url: https://gsd.readthedocs.io
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - bdice
    - joaander
