{% set name = "gsd" %}
{% set version = "1.5.4" %}
{% set sha256 = "09b09f1316c809dae96b1a02972673ef928eb549fcc1cae484265590a5b4acff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # the upstream package does not support windows
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - setuptools
    - cython
    - python
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - gsd
    - gsd.fl
    - gsd.pygsd
    - gsd.hoomd
  source_files:
    - tests/
    - setup.cfg
  commands:
    - nosetests  # [py3k]

about:
  home: https://bitbucket.org/glotzer/gsd
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'General simulation data'

  description: |
   GSD (General Simulation Data) is a file format specification
   and a library to read and write it. The package also contains a python module
   that reads and writes hoomd schema gsd files with an easy to use syntax.

  doc_url: https://gsd.readthedocs.io
  dev_url: https://bitbucket.org/glotzer/gsd

extra:
  recipe-maintainers:
    - joaander
