{% set name = "gsd" %}
{% set version = "1.5.3" %}
{% set sha256 = "84fad6e1c60e80ad8a4c911efe1af11e4e74f66b315e5b8336a1861f432c76ee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - toolchain

  run:
    - python
    - numpy >=1.11

test:
  imports:
    - gsd
    - gsd.fl
    - gsd.pygsd
    - gsd.hoomd

about:
  home: https://bitbucket.org/glotzer/gsd
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'General simulation data'

  description: |
   GSD (General Simulation Data) is a file format specification
   and a library to read and write it. The package also contains a python module
   that reads and writes hoomd schema gsd files with an easy to use syntax.

  doc_url: https://gsd.readthedocs.io
  dev_url: https://bitbucket.org/glotzer/gsd

extra:
  recipe-maintainers:
    - joaander
