{% set name = "gsd" %}
{% set version = "3.4.0" %}
{% set sha256 = "ad5012961964efe19797b5ee21b0332d48e9e1655e4781f92cfaaac2b6c69d55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/{{ name }}/releases/download/v{{ version }}/gsd-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # the upstream package does not support python2.7
  skip: true  # [py<=27]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - setuptools
    - cython
    - python
    - numpy >=2
    - pip

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - gsd
    - gsd.fl
    - gsd.pygsd
    - gsd.hoomd
  commands:
    - cd /
    - pytest --pyargs gsd -v -ra --ignore-glob="*largefile*"

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: General simulation data

  description: |
    GSD (General Simulation Data) is a file format specification
    and a library to read and write it. The package also contains a python module
    that reads and writes hoomd schema gsd files with an easy to use syntax.

  doc_url: https://gsd.readthedocs.io
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - bdice
    - joaander
