schema_version: 1

context:
  name: gsd
  version: 4.1.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/glotzerlab/${{ name }}/releases/download/v${{ version }}/gsd-${{ version }}.tar.gz
  sha256: 24668bb44e89e5fd93f598433f711e3f11fa226fb6b73e5c8f3b1f9ba40f4692

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python                                 
        - cross-python_${{ target_platform }}
        - cython >= 3.1
        - numpy >=2                                  

  host:
    - setuptools >=77
    - cython >=3.1
    - python
    - numpy >=2
    - pip

  run:
    - python

tests:
  - script:
    - cd /
    - pytest --pyargs gsd -v -ra --ignore-glob="*largefile*"
    requires:
      - pytest

about:
  homepage: https://github.com/glotzerlab/${{ name }}
  license: BSD-2-Clause
  license: BSD
  license_file: LICENSE
  summary: General simulation data

  description: |
    GSD (General Simulation Data) is a file format specification
    and a library to read and write it. The package also contains a python module
    that reads and writes hoomd schema gsd files with an easy to use syntax.

  documentation: https://gsd.readthedocs.io
  repository: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - joaander
    - tcmoore3
    - SchoeniPhlippsn
    - DomFijan
    - janbridley
    - tfteague
    - sumitavaumich
